"""Add User model for Supabase auth integration

Revision ID: c6b123598855
Revises: 4a6557fd3034
Create Date: 2025-07-10 15:45:54.551353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6b123598855'
down_revision = '4a6557fd3034'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 